### ISSUE TITLE
Add Makeup Try-on functionality

### ISSUE THREAD

**Issue by bkmehta93** [designhubz-org/android-example#8]
The android-sdk has been updated to add the Makeup Try-on support. Need to update the example app to have this functionality as well.

**Comment by nickjtch** [comment]
@bkmehta93  there is an error we're getting in the new app version where the `Please wait` remains on the screen even after the widget loads.

**Comment by bkmehta93** [comment]
@nickjtch The JSON data received inside onProgressCallback is causing a JSONException. Here is the data the app is getting inside onProgressCallback:
`[{"messageId":"1","command":"2","data":1},"37699","progressCallback"]`
The format of the JSON seems to have been changed. For instance, previously we had "command":"progressCallback". I think we need to revert back the JSON response that seems to have been changed recently.

**Comment by nickjtch** [comment]
@bkmehta93 this should be resolved now.
